[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]

[advisories]
yanked = "deny"
ignore = []

[bans]
multiple-versions = "allow" # We don't maintain Cargo lockfile, so this isn't really feasible to deny
wildcards = "deny"          # Dependencies should not have be specified with '*'

[sources]
unknown-registry = "deny" # crates.io is allowed and a known register by default
unknown-git = "deny"
